#! /usr/bin/env python

import pandas as pd
import sys

output_file, certificates_file, addresses_file = sys.argv[1:]

columns_to_keep = [
    'POSTCODE',
    'TOTAL_FLOOR_AREA',
    'PROPERTY_TYPE',
]

certificate_df = pd.read_csv(certificates_file, usecols=columns_to_keep)
addresses_df = pd.read_csv(addresses_file)

certificate_df['FULL_ADDRESS'] = addresses_df.iloc[:,0]

with open(output_file, 'w') as f:
    certificate_df.to_csv(f, index=False)
